import type { CitaBook } from "@/lib/gospel/types";

/** Liturgical / Spanish names and abbreviations → USFM book id. */
const ALIASES: Record<string, string> = {
  gen: "GEN",
  genesis: "GEN",
  gn: "GEN",
  exo: "EXO",
  exodo: "EXO",
  ex: "EXO",
  lev: "LEV",
  levitico: "LEV",
  lv: "LEV",
  num: "NUM",
  numeros: "NUM",
  nm: "NUM",
  deu: "DEU",
  deuteronomio: "DEU",
  dt: "DEU",
  jos: "JOS",
  josue: "JOS",
  jdg: "JDG",
  jueces: "JDG",
  jc: "JDG",
  rut: "RUT",
  rt: "RUT",
  "1sa": "1SA",
  "1samuel": "1SA",
  samuelsamuel: "1SA",
  "1sam": "1SA",
  "2sa": "2SA",
  "2samuel": "2SA",
  "2sam": "2SA",
  "1ki": "1KI",
  "1reyes": "1KI",
  "1re": "1KI",
  "1r": "1KI",
  "2ki": "2KI",
  "2reyes": "2KI",
  "2re": "2KI",
  "2r": "2KI",
  "1ch": "1CH",
  "1cronicas": "1CH",
  "1cr": "1CH",
  "2ch": "2CH",
  "2cronicas": "2CH",
  "2cr": "2CH",
  ezr: "EZR",
  esdras: "EZR",
  esd: "EZR",
  neh: "NEH",
  nehemias: "NEH",
  ne: "NEH",
  est: "EST",
  ester: "EST",
  job: "JOB",
  psa: "PSA",
  salmos: "PSA",
  salmo: "PSA",
  sal: "PSA",
  sl: "PSA",
  pro: "PRO",
  proverbios: "PRO",
  prv: "PRO",
  ecc: "ECC",
  eclesiastes: "ECC",
  qohelet: "ECC",
  qos: "ECC",
  sng: "SNG",
  cantar: "SNG",
  cantardeloscantares: "SNG",
  cnt: "SNG",
  ct: "SNG",
  isa: "ISA",
  isaias: "ISA",
  is: "ISA",
  jer: "JER",
  jeremias: "JER",
  jr: "JER",
  lam: "LAM",
  lamentaciones: "LAM",
  eze: "EZE",
  ezequiel: "EZE",
  ez: "EZE",
  dan: "DAN",
  daniel: "DAN",
  dn: "DAN",
  hos: "HOS",
  oseas: "HOS",
  os: "HOS",
  jol: "JOL",
  joel: "JOL",
  jl: "JOL",
  amo: "AMO",
  amos: "AMO",
  am: "AMO",
  oba: "OBA",
  abdias: "OBA",
  ab: "OBA",
  jon: "JON",
  jonas: "JON",
  mic: "MIC",
  miqueas: "MIC",
  mi: "MIC",
  nam: "NAM",
  nahum: "NAM",
  na: "NAM",
  hab: "HAB",
  habacuc: "HAB",
  zep: "ZEP",
  sofonias: "ZEP",
  sof: "ZEP",
  hag: "HAG",
  ageo: "HAG",
  ag: "HAG",
  zec: "ZEC",
  zacarias: "ZEC",
  zac: "ZEC",
  za: "ZEC",
  mal: "MAL",
  malaquias: "MAL",
  tob: "TOB",
  tobias: "TOB",
  tb: "TOB",
  jdt: "JDT",
  judit: "JDT",
  jt: "JDT",
  esg: "ESG",
  estergriego: "ESG",
  estersuplementosgriegos: "ESG",
  wis: "WIS",
  sabiduria: "WIS",
  sab: "WIS",
  sir: "SIR",
  eclesiastico: "SIR",
  eclo: "SIR",
  si: "SIR",
  bar: "BAR",
  baruc: "BAR",
  lje: "LJE",
  cartadejeremias: "LJE",
  s3y: "S3Y",
  sus: "SUS",
  susana: "SUS",
  bel: "BEL",
  "1ma": "1MA",
  "1macabeos": "1MA",
  "1mac": "1MA",
  "1m": "1MA",
  "2ma": "2MA",
  "2macabeos": "2MA",
  "2mac": "2MA",
  "2m": "2MA",
  mat: "MAT",
  mt: "MAT",
  mateo: "MAT",
  sanmateo: "MAT",
  evangeliosegunsanmateo: "MAT",
  matthew: "MAT",
  mrk: "MRK",
  mc: "MRK",
  mk: "MRK",
  marcos: "MRK",
  sanmarcos: "MRK",
  evangeliosegunsanmarcos: "MRK",
  mark: "MRK",
  luk: "LUK",
  lc: "LUK",
  lk: "LUK",
  lucas: "LUK",
  sanlucas: "LUK",
  evangeliosegunsanlucas: "LUK",
  luke: "LUK",
  jhn: "JHN",
  jn: "JHN",
  juan: "JHN",
  sanjuan: "JHN",
  evangeliosegunsanjuan: "JHN",
  john: "JHN",
  act: "ACT",
  hch: "ACT",
  hechos: "ACT",
  hechosdelosapostoles: "ACT",
  acts: "ACT",
  ac: "ACT",
  rom: "ROM",
  romanos: "ROM",
  rm: "ROM",
  "1co": "1CO",
  "1corintios": "1CO",
  "1cor": "1CO",
  "2co": "2CO",
  "2corintios": "2CO",
  "2cor": "2CO",
  gal: "GAL",
  galatas: "GAL",
  ga: "GAL",
  eph: "EPH",
  efesios: "EPH",
  ef: "EPH",
  php: "PHP",
  filipenses: "PHP",
  flp: "PHP",
  col: "COL",
  colosenses: "COL",
  "1th": "1TH",
  "1tesalonicenses": "1TH",
  "1tes": "1TH",
  "1ts": "1TH",
  "2th": "2TH",
  "2tesalonicenses": "2TH",
  "2tes": "2TH",
  "2ts": "2TH",
  "1ti": "1TI",
  "1timoteo": "1TI",
  "1tim": "1TI",
  "2ti": "2TI",
  "2timoteo": "2TI",
  "2tim": "2TI",
  tit: "TIT",
  tito: "TIT",
  phm: "PHM",
  filemon: "PHM",
  flm: "PHM",
  heb: "HEB",
  hebreos: "HEB",
  jas: "JAS",
  santiago: "JAS",
  st: "JAS",
  "1pe": "1PE",
  "1pedro": "1PE",
  "1p": "1PE",
  "2pe": "2PE",
  "2pedro": "2PE",
  "2p": "2PE",
  "1jn": "1JN",
  "1juan": "1JN",
  "2jn": "2JN",
  "2juan": "2JN",
  "3jn": "3JN",
  "3juan": "3JN",
  jud: "JUD",
  judas: "JUD",
  rev: "REV",
  apocalipsis: "REV",
  ap: "REV",
  apo: "REV",
};

export const CITA_TO_USFM: Record<CitaBook, string> = {
  mt: "MAT",
  mc: "MRK",
  lc: "LUK",
  jn: "JHN",
  hch: "ACT",
};

export function foldBookKey(raw: string): string {
  return raw
    .normalize("NFD")
    .replace(/\p{M}/gu, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "");
}

/** Map a Spanish name, liturgical abbreviation, CitaBook, or USFM id to USFM. */
export function bookToUsfm(raw: string): string | null {
  const key = foldBookKey(raw);
  if (!key) return null;
  return ALIASES[key] ?? null;
}

/** True only for a canonical USFM id (`LUK`, `1CO`), not `Lc` / `mt`. */
export function isUsfmId(raw: string): boolean {
  const id = raw.trim().toUpperCase();
  return Boolean(id) && bookToUsfm(id) === id;
}

export function citaBookToUsfm(book: CitaBook): string {
  return CITA_TO_USFM[book];
}

const USFM_TO_CITA = Object.fromEntries(
  Object.entries(CITA_TO_USFM).map(([cita, usfm]) => [usfm, cita]),
) as Record<string, CitaBook>;

export function usfmToCitaBook(usfm: string): CitaBook | null {
  return USFM_TO_CITA[usfm.trim().toUpperCase()] ?? null;
}
