/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CitasRouteImport } from './routes/citas'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as IngresarRouteImport } from './routes/ingresar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BibliaSlugRouteImport } from './routes/biblia.$slug'
import { Route as CitasIndexRouteImport } from './routes/citas.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitasRoute = CitasRouteImport.update({
  id: '/citas',
  path: '/citas',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const IngresarRoute = IngresarRouteImport.update({
  id: '/ingresar',
  path: '/ingresar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliaSlugRoute = BibliaSlugRouteImport.update({
  id: '/biblia/$slug',
  path: '/biblia/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CitasIndexRoute = CitasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CitasRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/citas': typeof CitasRouteWithChildren
  '/favoritos': typeof FavoritosRoute
  '/ingresar': typeof IngresarRoute
  '/login': typeof LoginRoute
  '/biblia/$slug': typeof BibliaSlugRoute
  '/citas/': typeof CitasIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favoritos': typeof FavoritosRoute
  '/ingresar': typeof IngresarRoute
  '/login': typeof LoginRoute
  '/biblia/$slug': typeof BibliaSlugRoute
  '/citas': typeof CitasIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/citas': typeof CitasRouteWithChildren
  '/favoritos': typeof FavoritosRoute
  '/ingresar': typeof IngresarRoute
  '/login': typeof LoginRoute
  '/biblia/$slug': typeof BibliaSlugRoute
  '/citas/': typeof CitasIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/citas'
    | '/favoritos'
    | '/ingresar'
    | '/login'
    | '/biblia/$slug'
    | '/citas/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favoritos'
    | '/ingresar'
    | '/login'
    | '/biblia/$slug'
    | '/citas'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/citas'
    | '/favoritos'
    | '/ingresar'
    | '/login'
    | '/biblia/$slug'
    | '/citas/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CitasRoute: typeof CitasRouteWithChildren
  FavoritosRoute: typeof FavoritosRoute
  IngresarRoute: typeof IngresarRoute
  LoginRoute: typeof LoginRoute
  BibliaSlugRoute: typeof BibliaSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citas': {
      id: '/citas'
      path: '/citas'
      fullPath: '/citas'
      preLoaderRoute: typeof CitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingresar': {
      id: '/ingresar'
      path: '/ingresar'
      fullPath: '/ingresar'
      preLoaderRoute: typeof IngresarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblia/$slug': {
      id: '/biblia/$slug'
      path: '/biblia/$slug'
      fullPath: '/biblia/$slug'
      preLoaderRoute: typeof BibliaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citas/': {
      id: '/citas/'
      path: '/'
      fullPath: '/citas/'
      preLoaderRoute: typeof CitasIndexRouteImport
      parentRoute: typeof CitasRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CitasRouteChildren {
  CitasIndexRoute: typeof CitasIndexRoute
}

const CitasRouteChildren: CitasRouteChildren = {
  CitasIndexRoute: CitasIndexRoute,
}

const CitasRouteWithChildren = CitasRoute._addFileChildren(CitasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CitasRoute: CitasRouteWithChildren,
  FavoritosRoute: FavoritosRoute,
  IngresarRoute: IngresarRoute,
  LoginRoute: LoginRoute,
  BibliaSlugRoute: BibliaSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
