/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CitasRouteImport } from './routes/citas'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as IngresarRouteImport } from './routes/ingresar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CitasIndexRouteImport } from './routes/citas.index'
import { Route as CitasRefRouteImport } from './routes/citas.$ref'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as CitaBookPinRouteImport } from './routes/cita.$book.$pin'
import { Route as CitasBookPinRouteImport } from './routes/citas.$book.$pin'
import { Route as OgCitaRefRouteImport } from './routes/og.cita.$ref'
import { Route as OgCitaBookPinRouteImport } from './routes/og.cita.$book.$pin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitasRoute = CitasRouteImport.update({
  id: '/citas',
  path: '/citas',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const IngresarRoute = IngresarRouteImport.update({
  id: '/ingresar',
  path: '/ingresar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CitasIndexRoute = CitasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CitasRoute,
} as any)
const CitasRefRoute = CitasRefRouteImport.update({
  id: '/$ref',
  path: '/$ref',
  getParentRoute: () => CitasRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CitaBookPinRoute = CitaBookPinRouteImport.update({
  id: '/cita/$book/$pin',
  path: '/cita/$book/$pin',
  getParentRoute: () => rootRouteImport,
} as any)
const CitasBookPinRoute = CitasBookPinRouteImport.update({
  id: '/$book/$pin',
  path: '/$book/$pin',
  getParentRoute: () => CitasRoute,
} as any)
const OgCitaRefRoute = OgCitaRefRouteImport.update({
  id: '/og/cita/$ref',
  path: '/og/cita/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const OgCitaBookPinRoute = OgCitaBookPinRouteImport.update({
  id: '/og/cita/$book/$pin',
  path: '/og/cita/$book/$pin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/citas': typeof CitasRouteWithChildren
  '/favoritos': typeof FavoritosRoute
  '/ingresar': typeof IngresarRoute
  '/login': typeof LoginRoute
  '/citas/$ref': typeof CitasRefRoute
  '/citas/': typeof CitasIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/cita/$book/$pin': typeof CitaBookPinRoute
  '/citas/$book/$pin': typeof CitasBookPinRoute
  '/og/cita/$ref': typeof OgCitaRefRoute
  '/og/cita/$book/$pin': typeof OgCitaBookPinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favoritos': typeof FavoritosRoute
  '/ingresar': typeof IngresarRoute
  '/login': typeof LoginRoute
  '/citas/$ref': typeof CitasRefRoute
  '/citas': typeof CitasIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/cita/$book/$pin': typeof CitaBookPinRoute
  '/citas/$book/$pin': typeof CitasBookPinRoute
  '/og/cita/$ref': typeof OgCitaRefRoute
  '/og/cita/$book/$pin': typeof OgCitaBookPinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/citas': typeof CitasRouteWithChildren
  '/favoritos': typeof FavoritosRoute
  '/ingresar': typeof IngresarRoute
  '/login': typeof LoginRoute
  '/citas/$ref': typeof CitasRefRoute
  '/citas/': typeof CitasIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/cita/$book/$pin': typeof CitaBookPinRoute
  '/citas/$book/$pin': typeof CitasBookPinRoute
  '/og/cita/$ref': typeof OgCitaRefRoute
  '/og/cita/$book/$pin': typeof OgCitaBookPinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/citas'
    | '/favoritos'
    | '/ingresar'
    | '/login'
    | '/citas/$ref'
    | '/citas/'
    | '/api/auth/$'
    | '/cita/$book/$pin'
    | '/citas/$book/$pin'
    | '/og/cita/$ref'
    | '/og/cita/$book/$pin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favoritos'
    | '/ingresar'
    | '/login'
    | '/citas/$ref'
    | '/citas'
    | '/api/auth/$'
    | '/cita/$book/$pin'
    | '/citas/$book/$pin'
    | '/og/cita/$ref'
    | '/og/cita/$book/$pin'
  id:
    | '__root__'
    | '/'
    | '/citas'
    | '/favoritos'
    | '/ingresar'
    | '/login'
    | '/citas/$ref'
    | '/citas/'
    | '/api/auth/$'
    | '/cita/$book/$pin'
    | '/citas/$book/$pin'
    | '/og/cita/$ref'
    | '/og/cita/$book/$pin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CitasRoute: typeof CitasRouteWithChildren
  FavoritosRoute: typeof FavoritosRoute
  IngresarRoute: typeof IngresarRoute
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  CitaBookPinRoute: typeof CitaBookPinRoute
  OgCitaRefRoute: typeof OgCitaRefRoute
  OgCitaBookPinRoute: typeof OgCitaBookPinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citas': {
      id: '/citas'
      path: '/citas'
      fullPath: '/citas'
      preLoaderRoute: typeof CitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingresar': {
      id: '/ingresar'
      path: '/ingresar'
      fullPath: '/ingresar'
      preLoaderRoute: typeof IngresarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citas/': {
      id: '/citas/'
      path: '/'
      fullPath: '/citas/'
      preLoaderRoute: typeof CitasIndexRouteImport
      parentRoute: typeof CitasRoute
    }
    '/citas/$ref': {
      id: '/citas/$ref'
      path: '/$ref'
      fullPath: '/citas/$ref'
      preLoaderRoute: typeof CitasRefRouteImport
      parentRoute: typeof CitasRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cita/$book/$pin': {
      id: '/cita/$book/$pin'
      path: '/cita/$book/$pin'
      fullPath: '/cita/$book/$pin'
      preLoaderRoute: typeof CitaBookPinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citas/$book/$pin': {
      id: '/citas/$book/$pin'
      path: '/$book/$pin'
      fullPath: '/citas/$book/$pin'
      preLoaderRoute: typeof CitasBookPinRouteImport
      parentRoute: typeof CitasRoute
    }
    '/og/cita/$ref': {
      id: '/og/cita/$ref'
      path: '/og/cita/$ref'
      fullPath: '/og/cita/$ref'
      preLoaderRoute: typeof OgCitaRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/cita/$book/$pin': {
      id: '/og/cita/$book/$pin'
      path: '/og/cita/$book/$pin'
      fullPath: '/og/cita/$book/$pin'
      preLoaderRoute: typeof OgCitaBookPinRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CitasRouteChildren {
  CitasRefRoute: typeof CitasRefRoute
  CitasIndexRoute: typeof CitasIndexRoute
  CitasBookPinRoute: typeof CitasBookPinRoute
}

const CitasRouteChildren: CitasRouteChildren = {
  CitasRefRoute: CitasRefRoute,
  CitasIndexRoute: CitasIndexRoute,
  CitasBookPinRoute: CitasBookPinRoute,
}

const CitasRouteWithChildren = CitasRoute._addFileChildren(CitasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CitasRoute: CitasRouteWithChildren,
  FavoritosRoute: FavoritosRoute,
  IngresarRoute: IngresarRoute,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  CitaBookPinRoute: CitaBookPinRoute,
  OgCitaRefRoute: OgCitaRefRoute,
  OgCitaBookPinRoute: OgCitaBookPinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
